name: roulette_game_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.2.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  flutter_native_splash: ^2.3.6
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  flutter_timer_countdown: ^1.0.7

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.1.1
  build_runner: ^2.4.4

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/images/elements/
     - assets/images/unsplash/
     - assets/images/onboarding/
     - assets/images/lobby/
     - assets/images/roulette/
     - assets/images/win/
     - assets/images/slots/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Italic.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
        - asset: fonts/Poppins-Black.ttf


flutter_native_splash:
  background_image: "assets/images/elements/bg.png"
  image: assets/images/unsplash/logo.png
  android: true
  ios: true

  android_12:
    color: "#05081F"
    image: assets/images/unsplash/logo.png